### ISSUE TITLE
Question about tamper line/ switch and other things

### ISSUE THREAD

**Issue by majbah-ha** [carlosefr/pialarm#1]
Hello Carlos,

First I want to thank you for this nice piece of programming. I discovered it last week and I am planning to implement it as my alarm system. I changed the standard "normally open" inputs to "normally closed", because as you mentioned it makes it more secure. If one of the wires get cut or the system fails it will not fail silently. Saying that I found one issue I like to change, It is about the tamper line. I like to have the tamper line always active no matter what the state of the alarm is. If somebody tries to open the case of the alarm system or tampering with one of the PIR sensors or cut a wire, the alarm will go off even if it is not armed. But I don't have any clue how to do it.
The other question is about; how to export the state of the pins to be read by another program as homeassistant. I am using flyte
mqtt-io, and I am wondering if it can be done internally without using another program

Thanks in advance, 
Max

**Comment by carlosefr** [comment]
**Disclaimer:** I make no promises that this code is fit to be used in a real-world alarm system. It was written mainly to explore the concepts.

Having said this...

Triggering the alarm on tampering even when not armed is something I haven't considered. But it sounds to me like that would be equivalent to having it always armed. The library already lets you arm the alarm with only a subset of the inputs enabled (by passing it a list of inputs to ignore).

External sirens usually have their own tampering alarm that's independent of the main controller (triggering on power cut and case opening), BTW.

As for getting the state of the inputs, there's the `unsealed_inputs` attribute. If you combine it with the list of inputs you know to be connected, you then know the current state of all the inputs.

The `alarm.py` script is meant as an example of using the library. If you want to integrate with other things, I'd suggest using it as a starting point for your own modifications.

**Comment by majbah-ha** [comment]
Thank you very much for the quick reaction..
I will see how it goes following your explanation..

Have a nice day..
